package pkcs11

import (
	"context"
	"errors"
)

// Random returns length bytes generated by the selected token. The operation
// uses a managed read-only session and may be retried after replacing a failed
// session because no caller-visible token object is created. A zero length is
// valid and returns the provider's zero-length result.
func (c *Client) Random(ctx context.Context, length int) ([]byte, error) {
	if length < 0 {
		return nil, errors.New("pkcs11: random length must not be negative")
	}
	var value []byte
	err := c.withSession(ctx, sessionOptions{Operation: "generate-random", Idempotent: true}, func(session *sessionLease) error {
		var err error
		value, err = session.GenerateRandom(ctx, length)
		return err
	})
	return value, err
}

// SeedRandom mixes caller-provided seed material into the token RNG when the
// module supports C_SeedRandom. PKCS #11 does not guarantee that every token
// accepts external seed material, nor that calling SeedRandom makes low-entropy
// input suitable as a cryptographic seed. The input remains owned by the caller.
func (c *Client) SeedRandom(ctx context.Context, seed []byte) error {
	return c.withSession(ctx, sessionOptions{Operation: "seed-random"}, func(session *sessionLease) error {
		return session.SeedRandom(ctx, seed)
	})
}
