/*
 * Code generated by internal/cmd/gencalls from the pinned OASIS PKCS #11
 * 3.2 pkcs11f.h header; DO NOT EDIT.
 *
 * The shared Go implementation identifies a Cryptoki operation by its generated
 * function ID and supplies only native scalar values and pointers. This file is
 * the cgo transport adapter: each switch case selects the correctly versioned
 * function table, casts every uintptr_t to the OASIS-declared C type, and makes
 * the typed indirect call. Missing tables and function pointers return
 * CKR_FUNCTION_NOT_SUPPORTED instead of being dereferenced.
 */
#ifndef P11X_CALLS_GEN_H
#define P11X_CALLS_GEN_H 1

/* Generic cgo transport used by the shared Go implementation. */
#define P11X_MAX_ARGUMENTS 10

static inline CK_RV p11x_dispatch(
    p11x_ctx *ctx,
    uint16_t function_id,
    size_t argument_count,
    uintptr_t a0,
    uintptr_t a1,
    uintptr_t a2,
    uintptr_t a3,
    uintptr_t a4,
    uintptr_t a5,
    uintptr_t a6,
    uintptr_t a7,
    uintptr_t a8,
    uintptr_t a9) {
  const uintptr_t arguments[10] = {a0, a1, a2, a3, a4, a5, a6, a7, a8, a9};
  switch (function_id) {
    case 0: {
      if (argument_count != 1) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_Initialize) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_Initialize((void *)(uintptr_t)arguments[0]);
    }
    case 1: {
      if (argument_count != 1) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_Finalize) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_Finalize((void *)(uintptr_t)arguments[0]);
    }
    case 2: {
      if (argument_count != 1) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_GetInfo) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_GetInfo((CK_INFO *)(uintptr_t)arguments[0]);
    }
    case 3: {
      if (argument_count != 1) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_GetFunctionList) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_GetFunctionList((CK_FUNCTION_LIST **)(uintptr_t)arguments[0]);
    }
    case 4: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_GetSlotList) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_GetSlotList((unsigned char)(uintptr_t)arguments[0], (CK_SLOT_ID *)(uintptr_t)arguments[1], (unsigned long *)(uintptr_t)arguments[2]);
    }
    case 5: {
      if (argument_count != 2) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_GetSlotInfo) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_GetSlotInfo((CK_SLOT_ID)(uintptr_t)arguments[0], (CK_SLOT_INFO *)(uintptr_t)arguments[1]);
    }
    case 6: {
      if (argument_count != 2) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_GetTokenInfo) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_GetTokenInfo((CK_SLOT_ID)(uintptr_t)arguments[0], (CK_TOKEN_INFO *)(uintptr_t)arguments[1]);
    }
    case 7: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_GetMechanismList) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_GetMechanismList((CK_SLOT_ID)(uintptr_t)arguments[0], (CK_MECHANISM_TYPE *)(uintptr_t)arguments[1], (unsigned long *)(uintptr_t)arguments[2]);
    }
    case 8: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_GetMechanismInfo) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_GetMechanismInfo((CK_SLOT_ID)(uintptr_t)arguments[0], (CK_MECHANISM_TYPE)(uintptr_t)arguments[1], (CK_MECHANISM_INFO *)(uintptr_t)arguments[2]);
    }
    case 9: {
      if (argument_count != 4) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_InitToken) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_InitToken((CK_SLOT_ID)(uintptr_t)arguments[0], (unsigned char *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2], (unsigned char *)(uintptr_t)arguments[3]);
    }
    case 10: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_InitPIN) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_InitPIN((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (unsigned char *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2]);
    }
    case 11: {
      if (argument_count != 5) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_SetPIN) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_SetPIN((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (unsigned char *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2], (unsigned char *)(uintptr_t)arguments[3], (unsigned long)(uintptr_t)arguments[4]);
    }
    case 12: {
      if (argument_count != 5) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_OpenSession) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_OpenSession((CK_SLOT_ID)(uintptr_t)arguments[0], (CK_FLAGS)(uintptr_t)arguments[1], (void *)(uintptr_t)arguments[2], (CK_NOTIFY)(uintptr_t)arguments[3], (CK_SESSION_HANDLE *)(uintptr_t)arguments[4]);
    }
    case 13: {
      if (argument_count != 1) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_CloseSession) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_CloseSession((CK_SESSION_HANDLE)(uintptr_t)arguments[0]);
    }
    case 14: {
      if (argument_count != 1) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_CloseAllSessions) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_CloseAllSessions((CK_SLOT_ID)(uintptr_t)arguments[0]);
    }
    case 15: {
      if (argument_count != 2) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_GetSessionInfo) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_GetSessionInfo((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_SESSION_INFO *)(uintptr_t)arguments[1]);
    }
    case 16: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_GetOperationState) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_GetOperationState((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (unsigned char *)(uintptr_t)arguments[1], (unsigned long *)(uintptr_t)arguments[2]);
    }
    case 17: {
      if (argument_count != 5) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_SetOperationState) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_SetOperationState((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (unsigned char *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2], (CK_OBJECT_HANDLE)(uintptr_t)arguments[3], (CK_OBJECT_HANDLE)(uintptr_t)arguments[4]);
    }
    case 18: {
      if (argument_count != 4) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_Login) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_Login((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_USER_TYPE)(uintptr_t)arguments[1], (unsigned char *)(uintptr_t)arguments[2], (unsigned long)(uintptr_t)arguments[3]);
    }
    case 19: {
      if (argument_count != 1) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_Logout) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_Logout((CK_SESSION_HANDLE)(uintptr_t)arguments[0]);
    }
    case 20: {
      if (argument_count != 4) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_CreateObject) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_CreateObject((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_ATTRIBUTE *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2], (CK_OBJECT_HANDLE *)(uintptr_t)arguments[3]);
    }
    case 21: {
      if (argument_count != 5) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_CopyObject) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_CopyObject((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_OBJECT_HANDLE)(uintptr_t)arguments[1], (CK_ATTRIBUTE *)(uintptr_t)arguments[2], (unsigned long)(uintptr_t)arguments[3], (CK_OBJECT_HANDLE *)(uintptr_t)arguments[4]);
    }
    case 22: {
      if (argument_count != 2) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_DestroyObject) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_DestroyObject((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_OBJECT_HANDLE)(uintptr_t)arguments[1]);
    }
    case 23: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_GetObjectSize) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_GetObjectSize((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_OBJECT_HANDLE)(uintptr_t)arguments[1], (unsigned long *)(uintptr_t)arguments[2]);
    }
    case 24: {
      if (argument_count != 4) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_GetAttributeValue) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_GetAttributeValue((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_OBJECT_HANDLE)(uintptr_t)arguments[1], (CK_ATTRIBUTE *)(uintptr_t)arguments[2], (unsigned long)(uintptr_t)arguments[3]);
    }
    case 25: {
      if (argument_count != 4) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_SetAttributeValue) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_SetAttributeValue((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_OBJECT_HANDLE)(uintptr_t)arguments[1], (CK_ATTRIBUTE *)(uintptr_t)arguments[2], (unsigned long)(uintptr_t)arguments[3]);
    }
    case 26: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_FindObjectsInit) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_FindObjectsInit((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_ATTRIBUTE *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2]);
    }
    case 27: {
      if (argument_count != 4) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_FindObjects) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_FindObjects((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_OBJECT_HANDLE *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2], (unsigned long *)(uintptr_t)arguments[3]);
    }
    case 28: {
      if (argument_count != 1) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_FindObjectsFinal) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_FindObjectsFinal((CK_SESSION_HANDLE)(uintptr_t)arguments[0]);
    }
    case 29: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_EncryptInit) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_EncryptInit((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_MECHANISM *)(uintptr_t)arguments[1], (CK_OBJECT_HANDLE)(uintptr_t)arguments[2]);
    }
    case 30: {
      if (argument_count != 5) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_Encrypt) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_Encrypt((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (unsigned char *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2], (unsigned char *)(uintptr_t)arguments[3], (unsigned long *)(uintptr_t)arguments[4]);
    }
    case 31: {
      if (argument_count != 5) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_EncryptUpdate) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_EncryptUpdate((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (unsigned char *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2], (unsigned char *)(uintptr_t)arguments[3], (unsigned long *)(uintptr_t)arguments[4]);
    }
    case 32: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_EncryptFinal) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_EncryptFinal((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (unsigned char *)(uintptr_t)arguments[1], (unsigned long *)(uintptr_t)arguments[2]);
    }
    case 33: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_DecryptInit) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_DecryptInit((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_MECHANISM *)(uintptr_t)arguments[1], (CK_OBJECT_HANDLE)(uintptr_t)arguments[2]);
    }
    case 34: {
      if (argument_count != 5) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_Decrypt) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_Decrypt((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (unsigned char *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2], (unsigned char *)(uintptr_t)arguments[3], (unsigned long *)(uintptr_t)arguments[4]);
    }
    case 35: {
      if (argument_count != 5) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_DecryptUpdate) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_DecryptUpdate((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (unsigned char *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2], (unsigned char *)(uintptr_t)arguments[3], (unsigned long *)(uintptr_t)arguments[4]);
    }
    case 36: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_DecryptFinal) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_DecryptFinal((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (unsigned char *)(uintptr_t)arguments[1], (unsigned long *)(uintptr_t)arguments[2]);
    }
    case 37: {
      if (argument_count != 2) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_DigestInit) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_DigestInit((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_MECHANISM *)(uintptr_t)arguments[1]);
    }
    case 38: {
      if (argument_count != 5) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_Digest) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_Digest((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (unsigned char *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2], (unsigned char *)(uintptr_t)arguments[3], (unsigned long *)(uintptr_t)arguments[4]);
    }
    case 39: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_DigestUpdate) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_DigestUpdate((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (unsigned char *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2]);
    }
    case 40: {
      if (argument_count != 2) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_DigestKey) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_DigestKey((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_OBJECT_HANDLE)(uintptr_t)arguments[1]);
    }
    case 41: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_DigestFinal) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_DigestFinal((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (unsigned char *)(uintptr_t)arguments[1], (unsigned long *)(uintptr_t)arguments[2]);
    }
    case 42: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_SignInit) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_SignInit((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_MECHANISM *)(uintptr_t)arguments[1], (CK_OBJECT_HANDLE)(uintptr_t)arguments[2]);
    }
    case 43: {
      if (argument_count != 5) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_Sign) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_Sign((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (unsigned char *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2], (unsigned char *)(uintptr_t)arguments[3], (unsigned long *)(uintptr_t)arguments[4]);
    }
    case 44: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_SignUpdate) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_SignUpdate((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (unsigned char *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2]);
    }
    case 45: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_SignFinal) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_SignFinal((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (unsigned char *)(uintptr_t)arguments[1], (unsigned long *)(uintptr_t)arguments[2]);
    }
    case 46: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_SignRecoverInit) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_SignRecoverInit((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_MECHANISM *)(uintptr_t)arguments[1], (CK_OBJECT_HANDLE)(uintptr_t)arguments[2]);
    }
    case 47: {
      if (argument_count != 5) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_SignRecover) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_SignRecover((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (unsigned char *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2], (unsigned char *)(uintptr_t)arguments[3], (unsigned long *)(uintptr_t)arguments[4]);
    }
    case 48: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_VerifyInit) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_VerifyInit((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_MECHANISM *)(uintptr_t)arguments[1], (CK_OBJECT_HANDLE)(uintptr_t)arguments[2]);
    }
    case 49: {
      if (argument_count != 5) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_Verify) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_Verify((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (unsigned char *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2], (unsigned char *)(uintptr_t)arguments[3], (unsigned long)(uintptr_t)arguments[4]);
    }
    case 50: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_VerifyUpdate) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_VerifyUpdate((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (unsigned char *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2]);
    }
    case 51: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_VerifyFinal) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_VerifyFinal((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (unsigned char *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2]);
    }
    case 52: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_VerifyRecoverInit) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_VerifyRecoverInit((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_MECHANISM *)(uintptr_t)arguments[1], (CK_OBJECT_HANDLE)(uintptr_t)arguments[2]);
    }
    case 53: {
      if (argument_count != 5) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_VerifyRecover) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_VerifyRecover((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (unsigned char *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2], (unsigned char *)(uintptr_t)arguments[3], (unsigned long *)(uintptr_t)arguments[4]);
    }
    case 54: {
      if (argument_count != 5) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_DigestEncryptUpdate) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_DigestEncryptUpdate((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (unsigned char *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2], (unsigned char *)(uintptr_t)arguments[3], (unsigned long *)(uintptr_t)arguments[4]);
    }
    case 55: {
      if (argument_count != 5) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_DecryptDigestUpdate) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_DecryptDigestUpdate((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (unsigned char *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2], (unsigned char *)(uintptr_t)arguments[3], (unsigned long *)(uintptr_t)arguments[4]);
    }
    case 56: {
      if (argument_count != 5) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_SignEncryptUpdate) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_SignEncryptUpdate((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (unsigned char *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2], (unsigned char *)(uintptr_t)arguments[3], (unsigned long *)(uintptr_t)arguments[4]);
    }
    case 57: {
      if (argument_count != 5) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_DecryptVerifyUpdate) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_DecryptVerifyUpdate((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (unsigned char *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2], (unsigned char *)(uintptr_t)arguments[3], (unsigned long *)(uintptr_t)arguments[4]);
    }
    case 58: {
      if (argument_count != 5) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_GenerateKey) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_GenerateKey((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_MECHANISM *)(uintptr_t)arguments[1], (CK_ATTRIBUTE *)(uintptr_t)arguments[2], (unsigned long)(uintptr_t)arguments[3], (CK_OBJECT_HANDLE *)(uintptr_t)arguments[4]);
    }
    case 59: {
      if (argument_count != 8) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_GenerateKeyPair) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_GenerateKeyPair((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_MECHANISM *)(uintptr_t)arguments[1], (CK_ATTRIBUTE *)(uintptr_t)arguments[2], (unsigned long)(uintptr_t)arguments[3], (CK_ATTRIBUTE *)(uintptr_t)arguments[4], (unsigned long)(uintptr_t)arguments[5], (CK_OBJECT_HANDLE *)(uintptr_t)arguments[6], (CK_OBJECT_HANDLE *)(uintptr_t)arguments[7]);
    }
    case 60: {
      if (argument_count != 6) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_WrapKey) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_WrapKey((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_MECHANISM *)(uintptr_t)arguments[1], (CK_OBJECT_HANDLE)(uintptr_t)arguments[2], (CK_OBJECT_HANDLE)(uintptr_t)arguments[3], (unsigned char *)(uintptr_t)arguments[4], (unsigned long *)(uintptr_t)arguments[5]);
    }
    case 61: {
      if (argument_count != 8) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_UnwrapKey) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_UnwrapKey((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_MECHANISM *)(uintptr_t)arguments[1], (CK_OBJECT_HANDLE)(uintptr_t)arguments[2], (unsigned char *)(uintptr_t)arguments[3], (unsigned long)(uintptr_t)arguments[4], (CK_ATTRIBUTE *)(uintptr_t)arguments[5], (unsigned long)(uintptr_t)arguments[6], (CK_OBJECT_HANDLE *)(uintptr_t)arguments[7]);
    }
    case 62: {
      if (argument_count != 6) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_DeriveKey) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_DeriveKey((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_MECHANISM *)(uintptr_t)arguments[1], (CK_OBJECT_HANDLE)(uintptr_t)arguments[2], (CK_ATTRIBUTE *)(uintptr_t)arguments[3], (unsigned long)(uintptr_t)arguments[4], (CK_OBJECT_HANDLE *)(uintptr_t)arguments[5]);
    }
    case 63: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_SeedRandom) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_SeedRandom((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (unsigned char *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2]);
    }
    case 64: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_GenerateRandom) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_GenerateRandom((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (unsigned char *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2]);
    }
    case 65: {
      if (argument_count != 1) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_GetFunctionStatus) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_GetFunctionStatus((CK_SESSION_HANDLE)(uintptr_t)arguments[0]);
    }
    case 66: {
      if (argument_count != 1) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_CancelFunction) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_CancelFunction((CK_SESSION_HANDLE)(uintptr_t)arguments[0]);
    }
    case 67: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_PTR f = p11x_base(ctx);
      if (!f || !f->C_WaitForSlotEvent) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_WaitForSlotEvent((CK_FLAGS)(uintptr_t)arguments[0], (CK_SLOT_ID *)(uintptr_t)arguments[1], (void *)(uintptr_t)arguments[2]);
    }
    case 68: {
      if (argument_count != 2) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_0_PTR f = p11x_v3(ctx);
      if (!f || !f->C_GetInterfaceList) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_GetInterfaceList((struct CK_INTERFACE *)(uintptr_t)arguments[0], (unsigned long *)(uintptr_t)arguments[1]);
    }
    case 69: {
      if (argument_count != 4) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_0_PTR f = p11x_v3(ctx);
      if (!f || !f->C_GetInterface) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_GetInterface((unsigned char *)(uintptr_t)arguments[0], (CK_VERSION *)(uintptr_t)arguments[1], (struct CK_INTERFACE **)(uintptr_t)arguments[2], (CK_FLAGS)(uintptr_t)arguments[3]);
    }
    case 70: {
      if (argument_count != 6) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_0_PTR f = p11x_v3(ctx);
      if (!f || !f->C_LoginUser) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_LoginUser((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_USER_TYPE)(uintptr_t)arguments[1], (unsigned char *)(uintptr_t)arguments[2], (unsigned long)(uintptr_t)arguments[3], (unsigned char *)(uintptr_t)arguments[4], (unsigned long)(uintptr_t)arguments[5]);
    }
    case 71: {
      if (argument_count != 2) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_0_PTR f = p11x_v3(ctx);
      if (!f || !f->C_SessionCancel) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_SessionCancel((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_FLAGS)(uintptr_t)arguments[1]);
    }
    case 72: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_0_PTR f = p11x_v3(ctx);
      if (!f || !f->C_MessageEncryptInit) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_MessageEncryptInit((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_MECHANISM *)(uintptr_t)arguments[1], (CK_OBJECT_HANDLE)(uintptr_t)arguments[2]);
    }
    case 73: {
      if (argument_count != 9) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_0_PTR f = p11x_v3(ctx);
      if (!f || !f->C_EncryptMessage) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_EncryptMessage((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (void *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2], (unsigned char *)(uintptr_t)arguments[3], (unsigned long)(uintptr_t)arguments[4], (unsigned char *)(uintptr_t)arguments[5], (unsigned long)(uintptr_t)arguments[6], (unsigned char *)(uintptr_t)arguments[7], (unsigned long *)(uintptr_t)arguments[8]);
    }
    case 74: {
      if (argument_count != 5) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_0_PTR f = p11x_v3(ctx);
      if (!f || !f->C_EncryptMessageBegin) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_EncryptMessageBegin((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (void *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2], (unsigned char *)(uintptr_t)arguments[3], (unsigned long)(uintptr_t)arguments[4]);
    }
    case 75: {
      if (argument_count != 8) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_0_PTR f = p11x_v3(ctx);
      if (!f || !f->C_EncryptMessageNext) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_EncryptMessageNext((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (void *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2], (unsigned char *)(uintptr_t)arguments[3], (unsigned long)(uintptr_t)arguments[4], (unsigned char *)(uintptr_t)arguments[5], (unsigned long *)(uintptr_t)arguments[6], (CK_FLAGS)(uintptr_t)arguments[7]);
    }
    case 76: {
      if (argument_count != 1) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_0_PTR f = p11x_v3(ctx);
      if (!f || !f->C_MessageEncryptFinal) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_MessageEncryptFinal((CK_SESSION_HANDLE)(uintptr_t)arguments[0]);
    }
    case 77: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_0_PTR f = p11x_v3(ctx);
      if (!f || !f->C_MessageDecryptInit) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_MessageDecryptInit((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_MECHANISM *)(uintptr_t)arguments[1], (CK_OBJECT_HANDLE)(uintptr_t)arguments[2]);
    }
    case 78: {
      if (argument_count != 9) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_0_PTR f = p11x_v3(ctx);
      if (!f || !f->C_DecryptMessage) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_DecryptMessage((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (void *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2], (unsigned char *)(uintptr_t)arguments[3], (unsigned long)(uintptr_t)arguments[4], (unsigned char *)(uintptr_t)arguments[5], (unsigned long)(uintptr_t)arguments[6], (unsigned char *)(uintptr_t)arguments[7], (unsigned long *)(uintptr_t)arguments[8]);
    }
    case 79: {
      if (argument_count != 5) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_0_PTR f = p11x_v3(ctx);
      if (!f || !f->C_DecryptMessageBegin) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_DecryptMessageBegin((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (void *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2], (unsigned char *)(uintptr_t)arguments[3], (unsigned long)(uintptr_t)arguments[4]);
    }
    case 80: {
      if (argument_count != 8) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_0_PTR f = p11x_v3(ctx);
      if (!f || !f->C_DecryptMessageNext) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_DecryptMessageNext((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (void *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2], (unsigned char *)(uintptr_t)arguments[3], (unsigned long)(uintptr_t)arguments[4], (unsigned char *)(uintptr_t)arguments[5], (unsigned long *)(uintptr_t)arguments[6], (CK_FLAGS)(uintptr_t)arguments[7]);
    }
    case 81: {
      if (argument_count != 1) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_0_PTR f = p11x_v3(ctx);
      if (!f || !f->C_MessageDecryptFinal) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_MessageDecryptFinal((CK_SESSION_HANDLE)(uintptr_t)arguments[0]);
    }
    case 82: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_0_PTR f = p11x_v3(ctx);
      if (!f || !f->C_MessageSignInit) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_MessageSignInit((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_MECHANISM *)(uintptr_t)arguments[1], (CK_OBJECT_HANDLE)(uintptr_t)arguments[2]);
    }
    case 83: {
      if (argument_count != 7) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_0_PTR f = p11x_v3(ctx);
      if (!f || !f->C_SignMessage) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_SignMessage((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (void *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2], (unsigned char *)(uintptr_t)arguments[3], (unsigned long)(uintptr_t)arguments[4], (unsigned char *)(uintptr_t)arguments[5], (unsigned long *)(uintptr_t)arguments[6]);
    }
    case 84: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_0_PTR f = p11x_v3(ctx);
      if (!f || !f->C_SignMessageBegin) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_SignMessageBegin((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (void *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2]);
    }
    case 85: {
      if (argument_count != 7) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_0_PTR f = p11x_v3(ctx);
      if (!f || !f->C_SignMessageNext) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_SignMessageNext((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (void *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2], (unsigned char *)(uintptr_t)arguments[3], (unsigned long)(uintptr_t)arguments[4], (unsigned char *)(uintptr_t)arguments[5], (unsigned long *)(uintptr_t)arguments[6]);
    }
    case 86: {
      if (argument_count != 1) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_0_PTR f = p11x_v3(ctx);
      if (!f || !f->C_MessageSignFinal) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_MessageSignFinal((CK_SESSION_HANDLE)(uintptr_t)arguments[0]);
    }
    case 87: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_0_PTR f = p11x_v3(ctx);
      if (!f || !f->C_MessageVerifyInit) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_MessageVerifyInit((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_MECHANISM *)(uintptr_t)arguments[1], (CK_OBJECT_HANDLE)(uintptr_t)arguments[2]);
    }
    case 88: {
      if (argument_count != 7) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_0_PTR f = p11x_v3(ctx);
      if (!f || !f->C_VerifyMessage) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_VerifyMessage((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (void *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2], (unsigned char *)(uintptr_t)arguments[3], (unsigned long)(uintptr_t)arguments[4], (unsigned char *)(uintptr_t)arguments[5], (unsigned long)(uintptr_t)arguments[6]);
    }
    case 89: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_0_PTR f = p11x_v3(ctx);
      if (!f || !f->C_VerifyMessageBegin) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_VerifyMessageBegin((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (void *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2]);
    }
    case 90: {
      if (argument_count != 7) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_0_PTR f = p11x_v3(ctx);
      if (!f || !f->C_VerifyMessageNext) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_VerifyMessageNext((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (void *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2], (unsigned char *)(uintptr_t)arguments[3], (unsigned long)(uintptr_t)arguments[4], (unsigned char *)(uintptr_t)arguments[5], (unsigned long)(uintptr_t)arguments[6]);
    }
    case 91: {
      if (argument_count != 1) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_0_PTR f = p11x_v3(ctx);
      if (!f || !f->C_MessageVerifyFinal) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_MessageVerifyFinal((CK_SESSION_HANDLE)(uintptr_t)arguments[0]);
    }
    case 92: {
      if (argument_count != 8) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_2_PTR f = p11x_v32(ctx);
      if (!f || !f->C_EncapsulateKey) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_EncapsulateKey((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_MECHANISM *)(uintptr_t)arguments[1], (CK_OBJECT_HANDLE)(uintptr_t)arguments[2], (CK_ATTRIBUTE *)(uintptr_t)arguments[3], (unsigned long)(uintptr_t)arguments[4], (unsigned char *)(uintptr_t)arguments[5], (unsigned long *)(uintptr_t)arguments[6], (CK_OBJECT_HANDLE *)(uintptr_t)arguments[7]);
    }
    case 93: {
      if (argument_count != 8) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_2_PTR f = p11x_v32(ctx);
      if (!f || !f->C_DecapsulateKey) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_DecapsulateKey((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_MECHANISM *)(uintptr_t)arguments[1], (CK_OBJECT_HANDLE)(uintptr_t)arguments[2], (CK_ATTRIBUTE *)(uintptr_t)arguments[3], (unsigned long)(uintptr_t)arguments[4], (unsigned char *)(uintptr_t)arguments[5], (unsigned long)(uintptr_t)arguments[6], (CK_OBJECT_HANDLE *)(uintptr_t)arguments[7]);
    }
    case 94: {
      if (argument_count != 5) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_2_PTR f = p11x_v32(ctx);
      if (!f || !f->C_VerifySignatureInit) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_VerifySignatureInit((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_MECHANISM *)(uintptr_t)arguments[1], (CK_OBJECT_HANDLE)(uintptr_t)arguments[2], (unsigned char *)(uintptr_t)arguments[3], (unsigned long)(uintptr_t)arguments[4]);
    }
    case 95: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_2_PTR f = p11x_v32(ctx);
      if (!f || !f->C_VerifySignature) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_VerifySignature((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (unsigned char *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2]);
    }
    case 96: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_2_PTR f = p11x_v32(ctx);
      if (!f || !f->C_VerifySignatureUpdate) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_VerifySignatureUpdate((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (unsigned char *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2]);
    }
    case 97: {
      if (argument_count != 1) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_2_PTR f = p11x_v32(ctx);
      if (!f || !f->C_VerifySignatureFinal) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_VerifySignatureFinal((CK_SESSION_HANDLE)(uintptr_t)arguments[0]);
    }
    case 98: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_2_PTR f = p11x_v32(ctx);
      if (!f || !f->C_GetSessionValidationFlags) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_GetSessionValidationFlags((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_SESSION_VALIDATION_FLAGS_TYPE)(uintptr_t)arguments[1], (CK_FLAGS *)(uintptr_t)arguments[2]);
    }
    case 99: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_2_PTR f = p11x_v32(ctx);
      if (!f || !f->C_AsyncComplete) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_AsyncComplete((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (unsigned char *)(uintptr_t)arguments[1], (CK_ASYNC_DATA *)(uintptr_t)arguments[2]);
    }
    case 100: {
      if (argument_count != 3) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_2_PTR f = p11x_v32(ctx);
      if (!f || !f->C_AsyncGetID) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_AsyncGetID((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (unsigned char *)(uintptr_t)arguments[1], (unsigned long *)(uintptr_t)arguments[2]);
    }
    case 101: {
      if (argument_count != 5) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_2_PTR f = p11x_v32(ctx);
      if (!f || !f->C_AsyncJoin) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_AsyncJoin((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (unsigned char *)(uintptr_t)arguments[1], (unsigned long)(uintptr_t)arguments[2], (unsigned char *)(uintptr_t)arguments[3], (unsigned long)(uintptr_t)arguments[4]);
    }
    case 102: {
      if (argument_count != 8) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_2_PTR f = p11x_v32(ctx);
      if (!f || !f->C_WrapKeyAuthenticated) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_WrapKeyAuthenticated((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_MECHANISM *)(uintptr_t)arguments[1], (CK_OBJECT_HANDLE)(uintptr_t)arguments[2], (CK_OBJECT_HANDLE)(uintptr_t)arguments[3], (unsigned char *)(uintptr_t)arguments[4], (unsigned long)(uintptr_t)arguments[5], (unsigned char *)(uintptr_t)arguments[6], (unsigned long *)(uintptr_t)arguments[7]);
    }
    case 103: {
      if (argument_count != 10) return CKR_ARGUMENTS_BAD;
      CK_FUNCTION_LIST_3_2_PTR f = p11x_v32(ctx);
      if (!f || !f->C_UnwrapKeyAuthenticated) return CKR_FUNCTION_NOT_SUPPORTED;
      return f->C_UnwrapKeyAuthenticated((CK_SESSION_HANDLE)(uintptr_t)arguments[0], (CK_MECHANISM *)(uintptr_t)arguments[1], (CK_OBJECT_HANDLE)(uintptr_t)arguments[2], (unsigned char *)(uintptr_t)arguments[3], (unsigned long)(uintptr_t)arguments[4], (CK_ATTRIBUTE *)(uintptr_t)arguments[5], (unsigned long)(uintptr_t)arguments[6], (unsigned char *)(uintptr_t)arguments[7], (unsigned long)(uintptr_t)arguments[8], (CK_OBJECT_HANDLE *)(uintptr_t)arguments[9]);
    }
    default:
      return CKR_FUNCTION_NOT_SUPPORTED;
  }
}

#endif
