// Code generated by internal/cmd/gencalls from the pinned OASIS PKCS #11 3.2 pkcs11f.h header; DO NOT EDIT.

package raw

type functionID uint16

const functionMaximumArguments = 10

const (
	functionInitialize functionID = iota
	functionFinalize
	functionGetInfo
	functionGetFunctionList
	functionGetSlotList
	functionGetSlotInfo
	functionGetTokenInfo
	functionGetMechanismList
	functionGetMechanismInfo
	functionInitToken
	functionInitPIN
	functionSetPIN
	functionOpenSession
	functionCloseSession
	functionCloseAllSessions
	functionGetSessionInfo
	functionGetOperationState
	functionSetOperationState
	functionLogin
	functionLogout
	functionCreateObject
	functionCopyObject
	functionDestroyObject
	functionGetObjectSize
	functionGetAttributeValue
	functionSetAttributeValue
	functionFindObjectsInit
	functionFindObjects
	functionFindObjectsFinal
	functionEncryptInit
	functionEncrypt
	functionEncryptUpdate
	functionEncryptFinal
	functionDecryptInit
	functionDecrypt
	functionDecryptUpdate
	functionDecryptFinal
	functionDigestInit
	functionDigest
	functionDigestUpdate
	functionDigestKey
	functionDigestFinal
	functionSignInit
	functionSign
	functionSignUpdate
	functionSignFinal
	functionSignRecoverInit
	functionSignRecover
	functionVerifyInit
	functionVerify
	functionVerifyUpdate
	functionVerifyFinal
	functionVerifyRecoverInit
	functionVerifyRecover
	functionDigestEncryptUpdate
	functionDecryptDigestUpdate
	functionSignEncryptUpdate
	functionDecryptVerifyUpdate
	functionGenerateKey
	functionGenerateKeyPair
	functionWrapKey
	functionUnwrapKey
	functionDeriveKey
	functionSeedRandom
	functionGenerateRandom
	functionGetFunctionStatus
	functionCancelFunction
	functionWaitForSlotEvent
	functionGetInterfaceList
	functionGetInterface
	functionLoginUser
	functionSessionCancel
	functionMessageEncryptInit
	functionEncryptMessage
	functionEncryptMessageBegin
	functionEncryptMessageNext
	functionMessageEncryptFinal
	functionMessageDecryptInit
	functionDecryptMessage
	functionDecryptMessageBegin
	functionDecryptMessageNext
	functionMessageDecryptFinal
	functionMessageSignInit
	functionSignMessage
	functionSignMessageBegin
	functionSignMessageNext
	functionMessageSignFinal
	functionMessageVerifyInit
	functionVerifyMessage
	functionVerifyMessageBegin
	functionVerifyMessageNext
	functionMessageVerifyFinal
	functionEncapsulateKey
	functionDecapsulateKey
	functionVerifySignatureInit
	functionVerifySignature
	functionVerifySignatureUpdate
	functionVerifySignatureFinal
	functionGetSessionValidationFlags
	functionAsyncComplete
	functionAsyncGetID
	functionAsyncJoin
	functionWrapKeyAuthenticated
	functionUnwrapKeyAuthenticated
	functionCount
)

type functionMetadata struct {
	name      string
	minimum   Version
	arguments uint8
}

var functionTableMetadata = [...]functionMetadata{
	functionInitialize:                {name: "C_Initialize", minimum: Version{Major: 0, Minor: 0}, arguments: 1},
	functionFinalize:                  {name: "C_Finalize", minimum: Version{Major: 0, Minor: 0}, arguments: 1},
	functionGetInfo:                   {name: "C_GetInfo", minimum: Version{Major: 0, Minor: 0}, arguments: 1},
	functionGetFunctionList:           {name: "C_GetFunctionList", minimum: Version{Major: 0, Minor: 0}, arguments: 1},
	functionGetSlotList:               {name: "C_GetSlotList", minimum: Version{Major: 0, Minor: 0}, arguments: 3},
	functionGetSlotInfo:               {name: "C_GetSlotInfo", minimum: Version{Major: 0, Minor: 0}, arguments: 2},
	functionGetTokenInfo:              {name: "C_GetTokenInfo", minimum: Version{Major: 0, Minor: 0}, arguments: 2},
	functionGetMechanismList:          {name: "C_GetMechanismList", minimum: Version{Major: 0, Minor: 0}, arguments: 3},
	functionGetMechanismInfo:          {name: "C_GetMechanismInfo", minimum: Version{Major: 0, Minor: 0}, arguments: 3},
	functionInitToken:                 {name: "C_InitToken", minimum: Version{Major: 0, Minor: 0}, arguments: 4},
	functionInitPIN:                   {name: "C_InitPIN", minimum: Version{Major: 0, Minor: 0}, arguments: 3},
	functionSetPIN:                    {name: "C_SetPIN", minimum: Version{Major: 0, Minor: 0}, arguments: 5},
	functionOpenSession:               {name: "C_OpenSession", minimum: Version{Major: 0, Minor: 0}, arguments: 5},
	functionCloseSession:              {name: "C_CloseSession", minimum: Version{Major: 0, Minor: 0}, arguments: 1},
	functionCloseAllSessions:          {name: "C_CloseAllSessions", minimum: Version{Major: 0, Minor: 0}, arguments: 1},
	functionGetSessionInfo:            {name: "C_GetSessionInfo", minimum: Version{Major: 0, Minor: 0}, arguments: 2},
	functionGetOperationState:         {name: "C_GetOperationState", minimum: Version{Major: 0, Minor: 0}, arguments: 3},
	functionSetOperationState:         {name: "C_SetOperationState", minimum: Version{Major: 0, Minor: 0}, arguments: 5},
	functionLogin:                     {name: "C_Login", minimum: Version{Major: 0, Minor: 0}, arguments: 4},
	functionLogout:                    {name: "C_Logout", minimum: Version{Major: 0, Minor: 0}, arguments: 1},
	functionCreateObject:              {name: "C_CreateObject", minimum: Version{Major: 0, Minor: 0}, arguments: 4},
	functionCopyObject:                {name: "C_CopyObject", minimum: Version{Major: 0, Minor: 0}, arguments: 5},
	functionDestroyObject:             {name: "C_DestroyObject", minimum: Version{Major: 0, Minor: 0}, arguments: 2},
	functionGetObjectSize:             {name: "C_GetObjectSize", minimum: Version{Major: 0, Minor: 0}, arguments: 3},
	functionGetAttributeValue:         {name: "C_GetAttributeValue", minimum: Version{Major: 0, Minor: 0}, arguments: 4},
	functionSetAttributeValue:         {name: "C_SetAttributeValue", minimum: Version{Major: 0, Minor: 0}, arguments: 4},
	functionFindObjectsInit:           {name: "C_FindObjectsInit", minimum: Version{Major: 0, Minor: 0}, arguments: 3},
	functionFindObjects:               {name: "C_FindObjects", minimum: Version{Major: 0, Minor: 0}, arguments: 4},
	functionFindObjectsFinal:          {name: "C_FindObjectsFinal", minimum: Version{Major: 0, Minor: 0}, arguments: 1},
	functionEncryptInit:               {name: "C_EncryptInit", minimum: Version{Major: 0, Minor: 0}, arguments: 3},
	functionEncrypt:                   {name: "C_Encrypt", minimum: Version{Major: 0, Minor: 0}, arguments: 5},
	functionEncryptUpdate:             {name: "C_EncryptUpdate", minimum: Version{Major: 0, Minor: 0}, arguments: 5},
	functionEncryptFinal:              {name: "C_EncryptFinal", minimum: Version{Major: 0, Minor: 0}, arguments: 3},
	functionDecryptInit:               {name: "C_DecryptInit", minimum: Version{Major: 0, Minor: 0}, arguments: 3},
	functionDecrypt:                   {name: "C_Decrypt", minimum: Version{Major: 0, Minor: 0}, arguments: 5},
	functionDecryptUpdate:             {name: "C_DecryptUpdate", minimum: Version{Major: 0, Minor: 0}, arguments: 5},
	functionDecryptFinal:              {name: "C_DecryptFinal", minimum: Version{Major: 0, Minor: 0}, arguments: 3},
	functionDigestInit:                {name: "C_DigestInit", minimum: Version{Major: 0, Minor: 0}, arguments: 2},
	functionDigest:                    {name: "C_Digest", minimum: Version{Major: 0, Minor: 0}, arguments: 5},
	functionDigestUpdate:              {name: "C_DigestUpdate", minimum: Version{Major: 0, Minor: 0}, arguments: 3},
	functionDigestKey:                 {name: "C_DigestKey", minimum: Version{Major: 0, Minor: 0}, arguments: 2},
	functionDigestFinal:               {name: "C_DigestFinal", minimum: Version{Major: 0, Minor: 0}, arguments: 3},
	functionSignInit:                  {name: "C_SignInit", minimum: Version{Major: 0, Minor: 0}, arguments: 3},
	functionSign:                      {name: "C_Sign", minimum: Version{Major: 0, Minor: 0}, arguments: 5},
	functionSignUpdate:                {name: "C_SignUpdate", minimum: Version{Major: 0, Minor: 0}, arguments: 3},
	functionSignFinal:                 {name: "C_SignFinal", minimum: Version{Major: 0, Minor: 0}, arguments: 3},
	functionSignRecoverInit:           {name: "C_SignRecoverInit", minimum: Version{Major: 0, Minor: 0}, arguments: 3},
	functionSignRecover:               {name: "C_SignRecover", minimum: Version{Major: 0, Minor: 0}, arguments: 5},
	functionVerifyInit:                {name: "C_VerifyInit", minimum: Version{Major: 0, Minor: 0}, arguments: 3},
	functionVerify:                    {name: "C_Verify", minimum: Version{Major: 0, Minor: 0}, arguments: 5},
	functionVerifyUpdate:              {name: "C_VerifyUpdate", minimum: Version{Major: 0, Minor: 0}, arguments: 3},
	functionVerifyFinal:               {name: "C_VerifyFinal", minimum: Version{Major: 0, Minor: 0}, arguments: 3},
	functionVerifyRecoverInit:         {name: "C_VerifyRecoverInit", minimum: Version{Major: 0, Minor: 0}, arguments: 3},
	functionVerifyRecover:             {name: "C_VerifyRecover", minimum: Version{Major: 0, Minor: 0}, arguments: 5},
	functionDigestEncryptUpdate:       {name: "C_DigestEncryptUpdate", minimum: Version{Major: 0, Minor: 0}, arguments: 5},
	functionDecryptDigestUpdate:       {name: "C_DecryptDigestUpdate", minimum: Version{Major: 0, Minor: 0}, arguments: 5},
	functionSignEncryptUpdate:         {name: "C_SignEncryptUpdate", minimum: Version{Major: 0, Minor: 0}, arguments: 5},
	functionDecryptVerifyUpdate:       {name: "C_DecryptVerifyUpdate", minimum: Version{Major: 0, Minor: 0}, arguments: 5},
	functionGenerateKey:               {name: "C_GenerateKey", minimum: Version{Major: 0, Minor: 0}, arguments: 5},
	functionGenerateKeyPair:           {name: "C_GenerateKeyPair", minimum: Version{Major: 0, Minor: 0}, arguments: 8},
	functionWrapKey:                   {name: "C_WrapKey", minimum: Version{Major: 0, Minor: 0}, arguments: 6},
	functionUnwrapKey:                 {name: "C_UnwrapKey", minimum: Version{Major: 0, Minor: 0}, arguments: 8},
	functionDeriveKey:                 {name: "C_DeriveKey", minimum: Version{Major: 0, Minor: 0}, arguments: 6},
	functionSeedRandom:                {name: "C_SeedRandom", minimum: Version{Major: 0, Minor: 0}, arguments: 3},
	functionGenerateRandom:            {name: "C_GenerateRandom", minimum: Version{Major: 0, Minor: 0}, arguments: 3},
	functionGetFunctionStatus:         {name: "C_GetFunctionStatus", minimum: Version{Major: 0, Minor: 0}, arguments: 1},
	functionCancelFunction:            {name: "C_CancelFunction", minimum: Version{Major: 0, Minor: 0}, arguments: 1},
	functionWaitForSlotEvent:          {name: "C_WaitForSlotEvent", minimum: Version{Major: 0, Minor: 0}, arguments: 3},
	functionGetInterfaceList:          {name: "C_GetInterfaceList", minimum: Version{Major: 3, Minor: 0}, arguments: 2},
	functionGetInterface:              {name: "C_GetInterface", minimum: Version{Major: 3, Minor: 0}, arguments: 4},
	functionLoginUser:                 {name: "C_LoginUser", minimum: Version{Major: 3, Minor: 0}, arguments: 6},
	functionSessionCancel:             {name: "C_SessionCancel", minimum: Version{Major: 3, Minor: 0}, arguments: 2},
	functionMessageEncryptInit:        {name: "C_MessageEncryptInit", minimum: Version{Major: 3, Minor: 0}, arguments: 3},
	functionEncryptMessage:            {name: "C_EncryptMessage", minimum: Version{Major: 3, Minor: 0}, arguments: 9},
	functionEncryptMessageBegin:       {name: "C_EncryptMessageBegin", minimum: Version{Major: 3, Minor: 0}, arguments: 5},
	functionEncryptMessageNext:        {name: "C_EncryptMessageNext", minimum: Version{Major: 3, Minor: 0}, arguments: 8},
	functionMessageEncryptFinal:       {name: "C_MessageEncryptFinal", minimum: Version{Major: 3, Minor: 0}, arguments: 1},
	functionMessageDecryptInit:        {name: "C_MessageDecryptInit", minimum: Version{Major: 3, Minor: 0}, arguments: 3},
	functionDecryptMessage:            {name: "C_DecryptMessage", minimum: Version{Major: 3, Minor: 0}, arguments: 9},
	functionDecryptMessageBegin:       {name: "C_DecryptMessageBegin", minimum: Version{Major: 3, Minor: 0}, arguments: 5},
	functionDecryptMessageNext:        {name: "C_DecryptMessageNext", minimum: Version{Major: 3, Minor: 0}, arguments: 8},
	functionMessageDecryptFinal:       {name: "C_MessageDecryptFinal", minimum: Version{Major: 3, Minor: 0}, arguments: 1},
	functionMessageSignInit:           {name: "C_MessageSignInit", minimum: Version{Major: 3, Minor: 0}, arguments: 3},
	functionSignMessage:               {name: "C_SignMessage", minimum: Version{Major: 3, Minor: 0}, arguments: 7},
	functionSignMessageBegin:          {name: "C_SignMessageBegin", minimum: Version{Major: 3, Minor: 0}, arguments: 3},
	functionSignMessageNext:           {name: "C_SignMessageNext", minimum: Version{Major: 3, Minor: 0}, arguments: 7},
	functionMessageSignFinal:          {name: "C_MessageSignFinal", minimum: Version{Major: 3, Minor: 0}, arguments: 1},
	functionMessageVerifyInit:         {name: "C_MessageVerifyInit", minimum: Version{Major: 3, Minor: 0}, arguments: 3},
	functionVerifyMessage:             {name: "C_VerifyMessage", minimum: Version{Major: 3, Minor: 0}, arguments: 7},
	functionVerifyMessageBegin:        {name: "C_VerifyMessageBegin", minimum: Version{Major: 3, Minor: 0}, arguments: 3},
	functionVerifyMessageNext:         {name: "C_VerifyMessageNext", minimum: Version{Major: 3, Minor: 0}, arguments: 7},
	functionMessageVerifyFinal:        {name: "C_MessageVerifyFinal", minimum: Version{Major: 3, Minor: 0}, arguments: 1},
	functionEncapsulateKey:            {name: "C_EncapsulateKey", minimum: Version{Major: 3, Minor: 2}, arguments: 8},
	functionDecapsulateKey:            {name: "C_DecapsulateKey", minimum: Version{Major: 3, Minor: 2}, arguments: 8},
	functionVerifySignatureInit:       {name: "C_VerifySignatureInit", minimum: Version{Major: 3, Minor: 2}, arguments: 5},
	functionVerifySignature:           {name: "C_VerifySignature", minimum: Version{Major: 3, Minor: 2}, arguments: 3},
	functionVerifySignatureUpdate:     {name: "C_VerifySignatureUpdate", minimum: Version{Major: 3, Minor: 2}, arguments: 3},
	functionVerifySignatureFinal:      {name: "C_VerifySignatureFinal", minimum: Version{Major: 3, Minor: 2}, arguments: 1},
	functionGetSessionValidationFlags: {name: "C_GetSessionValidationFlags", minimum: Version{Major: 3, Minor: 2}, arguments: 3},
	functionAsyncComplete:             {name: "C_AsyncComplete", minimum: Version{Major: 3, Minor: 2}, arguments: 3},
	functionAsyncGetID:                {name: "C_AsyncGetID", minimum: Version{Major: 3, Minor: 2}, arguments: 3},
	functionAsyncJoin:                 {name: "C_AsyncJoin", minimum: Version{Major: 3, Minor: 2}, arguments: 5},
	functionWrapKeyAuthenticated:      {name: "C_WrapKeyAuthenticated", minimum: Version{Major: 3, Minor: 2}, arguments: 8},
	functionUnwrapKeyAuthenticated:    {name: "C_UnwrapKeyAuthenticated", minimum: Version{Major: 3, Minor: 2}, arguments: 10},
}
