// Code generated by internal/cmd/genproxy; DO NOT EDIT.

package proxy

import raw "github.com/otpki/pkcs11/raw"

// SetOutputBufferPolicy forwards raw.Module.SetOutputBufferPolicy over one bounded proxy request.
func (c *Client) SetOutputBufferPolicy(policy raw.OutputBufferPolicy) {
	_ = c.invoke("SetOutputBufferPolicy", []any{policy})
}

// Initialize forwards raw.Module.Initialize over one bounded proxy request.
func (c *Client) Initialize() error {
	return c.invoke("Initialize", nil)
}

// InitializeLegacy forwards raw.Module.InitializeLegacy over one bounded proxy request.
func (c *Client) InitializeLegacy() error {
	return c.invoke("InitializeLegacy", nil)
}

// InitializeWithFlags forwards raw.Module.InitializeWithFlags over one bounded proxy request.
func (c *Client) InitializeWithFlags(flags uint) error {
	return c.invoke("InitializeWithFlags", []any{flags})
}

// Finalize forwards raw.Module.Finalize over one bounded proxy request.
func (c *Client) Finalize() error {
	return c.invoke("Finalize", nil)
}

// GetInfo forwards raw.Module.GetInfo over one bounded proxy request.
func (c *Client) GetInfo() (raw.Info, error) {
	var result0 raw.Info
	err := c.invoke("GetInfo", nil, &result0)
	return result0, err
}

// GetFunctionList forwards raw.Module.GetFunctionList over one bounded proxy request.
func (c *Client) GetFunctionList() (raw.FunctionListInfo, error) {
	var result0 raw.FunctionListInfo
	err := c.invoke("GetFunctionList", nil, &result0)
	return result0, err
}

// GetInterface forwards raw.Module.GetInterface over one bounded proxy request.
func (c *Client) GetInterface(name string, version *raw.Version, flags uint) (raw.FunctionListInfo, error) {
	var result0 raw.FunctionListInfo
	err := c.invoke("GetInterface", []any{name, version, flags}, &result0)
	return result0, err
}

// GetInterfaceList forwards raw.Module.GetInterfaceList over one bounded proxy request.
func (c *Client) GetInterfaceList() ([]raw.InterfaceInfo, error) {
	var result0 []raw.InterfaceInfo
	err := c.invoke("GetInterfaceList", nil, &result0)
	return result0, err
}

// GetSlotList forwards raw.Module.GetSlotList over one bounded proxy request.
func (c *Client) GetSlotList(tokenPresent bool) ([]raw.SlotID, error) {
	var result0 []raw.SlotID
	err := c.invoke("GetSlotList", []any{tokenPresent}, &result0)
	return result0, err
}

// GetSlotInfo forwards raw.Module.GetSlotInfo over one bounded proxy request.
func (c *Client) GetSlotInfo(slot raw.SlotID) (raw.SlotInfo, error) {
	var result0 raw.SlotInfo
	err := c.invoke("GetSlotInfo", []any{slot}, &result0)
	return result0, err
}

// GetTokenInfo forwards raw.Module.GetTokenInfo over one bounded proxy request.
func (c *Client) GetTokenInfo(slot raw.SlotID) (raw.TokenInfo, error) {
	var result0 raw.TokenInfo
	err := c.invoke("GetTokenInfo", []any{slot}, &result0)
	return result0, err
}

// GetMechanismList forwards raw.Module.GetMechanismList over one bounded proxy request.
func (c *Client) GetMechanismList(slot raw.SlotID) ([]raw.MechanismType, error) {
	var result0 []raw.MechanismType
	err := c.invoke("GetMechanismList", []any{slot}, &result0)
	return result0, err
}

// GetMechanismInfo forwards raw.Module.GetMechanismInfo over one bounded proxy request.
func (c *Client) GetMechanismInfo(slot raw.SlotID, mechanism raw.MechanismType) (raw.MechanismInfo, error) {
	var result0 raw.MechanismInfo
	err := c.invoke("GetMechanismInfo", []any{slot, mechanism}, &result0)
	return result0, err
}

// InitToken forwards raw.Module.InitToken over one bounded proxy request.
func (c *Client) InitToken(slot raw.SlotID, pin []byte, label string) error {
	return c.invoke("InitToken", []any{slot, pin, label})
}

// InitPIN forwards raw.Module.InitPIN over one bounded proxy request.
func (c *Client) InitPIN(session raw.SessionHandle, pin []byte) error {
	return c.invoke("InitPIN", []any{session, pin})
}

// SetPIN forwards raw.Module.SetPIN over one bounded proxy request.
func (c *Client) SetPIN(session raw.SessionHandle, oldPIN, newPIN []byte) error {
	return c.invoke("SetPIN", []any{session, oldPIN, newPIN})
}

// OpenSession forwards raw.Module.OpenSession over one bounded proxy request.
func (c *Client) OpenSession(slot raw.SlotID, flags uint) (raw.SessionHandle, error) {
	var result0 raw.SessionHandle
	err := c.invoke("OpenSession", []any{slot, flags}, &result0)
	return result0, err
}

// CloseSession forwards raw.Module.CloseSession over one bounded proxy request.
func (c *Client) CloseSession(session raw.SessionHandle) error {
	return c.invoke("CloseSession", []any{session})
}

// CloseAllSessions forwards raw.Module.CloseAllSessions over one bounded proxy request.
func (c *Client) CloseAllSessions(slot raw.SlotID) error {
	return c.invoke("CloseAllSessions", []any{slot})
}

// GetSessionInfo forwards raw.Module.GetSessionInfo over one bounded proxy request.
func (c *Client) GetSessionInfo(session raw.SessionHandle) (raw.SessionInfo, error) {
	var result0 raw.SessionInfo
	err := c.invoke("GetSessionInfo", []any{session}, &result0)
	return result0, err
}

// GetOperationState forwards raw.Module.GetOperationState over one bounded proxy request.
func (c *Client) GetOperationState(session raw.SessionHandle) ([]byte, error) {
	var result0 []byte
	err := c.invoke("GetOperationState", []any{session}, &result0)
	return result0, err
}

// SetOperationState forwards raw.Module.SetOperationState over one bounded proxy request.
func (c *Client) SetOperationState(session raw.SessionHandle, state []byte, encryptionKey, authenticationKey raw.ObjectHandle) error {
	return c.invoke("SetOperationState", []any{session, state, encryptionKey, authenticationKey})
}

// Login forwards raw.Module.Login over one bounded proxy request.
func (c *Client) Login(session raw.SessionHandle, userType uint, pin []byte) error {
	return c.invoke("Login", []any{session, userType, pin})
}

// LoginUser forwards raw.Module.LoginUser over one bounded proxy request.
func (c *Client) LoginUser(session raw.SessionHandle, userType uint, pin []byte, username string) error {
	return c.invoke("LoginUser", []any{session, userType, pin, username})
}

// Logout forwards raw.Module.Logout over one bounded proxy request.
func (c *Client) Logout(session raw.SessionHandle) error {
	return c.invoke("Logout", []any{session})
}

// SessionCancel forwards raw.Module.SessionCancel over one bounded proxy request.
func (c *Client) SessionCancel(session raw.SessionHandle, flags uint) error {
	return c.invoke("SessionCancel", []any{session, flags})
}

// GetFunctionStatus forwards raw.Module.GetFunctionStatus over one bounded proxy request.
func (c *Client) GetFunctionStatus(session raw.SessionHandle) error {
	return c.invoke("GetFunctionStatus", []any{session})
}

// CancelFunction forwards raw.Module.CancelFunction over one bounded proxy request.
func (c *Client) CancelFunction(session raw.SessionHandle) error {
	return c.invoke("CancelFunction", []any{session})
}

// WaitForSlotEvent forwards raw.Module.WaitForSlotEvent over one bounded proxy request.
func (c *Client) WaitForSlotEvent(flags uint) (raw.SlotID, error) {
	var result0 raw.SlotID
	err := c.invoke("WaitForSlotEvent", []any{flags}, &result0)
	return result0, err
}

// CreateObject forwards raw.Module.CreateObject over one bounded proxy request.
func (c *Client) CreateObject(session raw.SessionHandle, attributes []*raw.Attribute) (raw.ObjectHandle, error) {
	var result0 raw.ObjectHandle
	err := c.invoke("CreateObject", []any{session, attributes}, &result0)
	return result0, err
}

// CopyObject forwards raw.Module.CopyObject over one bounded proxy request.
func (c *Client) CopyObject(session raw.SessionHandle, object raw.ObjectHandle, attributes []*raw.Attribute) (raw.ObjectHandle, error) {
	var result0 raw.ObjectHandle
	err := c.invoke("CopyObject", []any{session, object, attributes}, &result0)
	return result0, err
}

// DestroyObject forwards raw.Module.DestroyObject over one bounded proxy request.
func (c *Client) DestroyObject(session raw.SessionHandle, object raw.ObjectHandle) error {
	return c.invoke("DestroyObject", []any{session, object})
}

// GetObjectSize forwards raw.Module.GetObjectSize over one bounded proxy request.
func (c *Client) GetObjectSize(session raw.SessionHandle, object raw.ObjectHandle) (uint, error) {
	var result0 uint
	err := c.invoke("GetObjectSize", []any{session, object}, &result0)
	return result0, err
}

// GetAttributeValue forwards raw.Module.GetAttributeValue over one bounded proxy request.
func (c *Client) GetAttributeValue(session raw.SessionHandle, object raw.ObjectHandle, attributes []*raw.Attribute) ([]*raw.Attribute, error) {
	var result0 []*raw.Attribute
	err := c.invoke("GetAttributeValue", []any{session, object, attributes}, &result0)
	return result0, err
}

// SetAttributeValue forwards raw.Module.SetAttributeValue over one bounded proxy request.
func (c *Client) SetAttributeValue(session raw.SessionHandle, object raw.ObjectHandle, attributes []*raw.Attribute) error {
	return c.invoke("SetAttributeValue", []any{session, object, attributes})
}

// FindObjectsInit forwards raw.Module.FindObjectsInit over one bounded proxy request.
func (c *Client) FindObjectsInit(session raw.SessionHandle, attributes []*raw.Attribute) error {
	return c.invoke("FindObjectsInit", []any{session, attributes})
}

// FindObjects forwards raw.Module.FindObjects over one bounded proxy request.
func (c *Client) FindObjects(session raw.SessionHandle, maxObjects int) ([]raw.ObjectHandle, bool, error) {
	var result0 []raw.ObjectHandle
	var result1 bool
	err := c.invoke("FindObjects", []any{session, maxObjects}, &result0, &result1)
	return result0, result1, err
}

// FindObjectsFinal forwards raw.Module.FindObjectsFinal over one bounded proxy request.
func (c *Client) FindObjectsFinal(session raw.SessionHandle) error {
	return c.invoke("FindObjectsFinal", []any{session})
}

// FindAllObjects forwards raw.Module.FindAllObjects over one bounded proxy request.
func (c *Client) FindAllObjects(session raw.SessionHandle, attributes []*raw.Attribute, batchSize int) ([]raw.ObjectHandle, error) {
	var result0 []raw.ObjectHandle
	err := c.invoke("FindAllObjects", []any{session, attributes, batchSize}, &result0)
	return result0, err
}

// EncryptInit forwards raw.Module.EncryptInit over one bounded proxy request.
func (c *Client) EncryptInit(session raw.SessionHandle, mechanisms []*raw.Mechanism, key raw.ObjectHandle) error {
	return c.invoke("EncryptInit", []any{session, mechanisms, key})
}

// Encrypt forwards raw.Module.Encrypt over one bounded proxy request.
func (c *Client) Encrypt(session raw.SessionHandle, plaintext []byte) ([]byte, error) {
	var result0 []byte
	err := c.invoke("Encrypt", []any{session, plaintext}, &result0)
	return result0, err
}

// EncryptUpdate forwards raw.Module.EncryptUpdate over one bounded proxy request.
func (c *Client) EncryptUpdate(session raw.SessionHandle, plaintext []byte) ([]byte, error) {
	var result0 []byte
	err := c.invoke("EncryptUpdate", []any{session, plaintext}, &result0)
	return result0, err
}

// EncryptFinal forwards raw.Module.EncryptFinal over one bounded proxy request.
func (c *Client) EncryptFinal(session raw.SessionHandle) ([]byte, error) {
	var result0 []byte
	err := c.invoke("EncryptFinal", []any{session}, &result0)
	return result0, err
}

// DecryptInit forwards raw.Module.DecryptInit over one bounded proxy request.
func (c *Client) DecryptInit(session raw.SessionHandle, mechanisms []*raw.Mechanism, key raw.ObjectHandle) error {
	return c.invoke("DecryptInit", []any{session, mechanisms, key})
}

// Decrypt forwards raw.Module.Decrypt over one bounded proxy request.
func (c *Client) Decrypt(session raw.SessionHandle, ciphertext []byte) ([]byte, error) {
	var result0 []byte
	err := c.invoke("Decrypt", []any{session, ciphertext}, &result0)
	return result0, err
}

// DecryptUpdate forwards raw.Module.DecryptUpdate over one bounded proxy request.
func (c *Client) DecryptUpdate(session raw.SessionHandle, ciphertext []byte) ([]byte, error) {
	var result0 []byte
	err := c.invoke("DecryptUpdate", []any{session, ciphertext}, &result0)
	return result0, err
}

// DecryptFinal forwards raw.Module.DecryptFinal over one bounded proxy request.
func (c *Client) DecryptFinal(session raw.SessionHandle) ([]byte, error) {
	var result0 []byte
	err := c.invoke("DecryptFinal", []any{session}, &result0)
	return result0, err
}

// DigestInit forwards raw.Module.DigestInit over one bounded proxy request.
func (c *Client) DigestInit(session raw.SessionHandle, mechanisms []*raw.Mechanism) error {
	return c.invoke("DigestInit", []any{session, mechanisms})
}

// Digest forwards raw.Module.Digest over one bounded proxy request.
func (c *Client) Digest(session raw.SessionHandle, data []byte) ([]byte, error) {
	var result0 []byte
	err := c.invoke("Digest", []any{session, data}, &result0)
	return result0, err
}

// DigestUpdate forwards raw.Module.DigestUpdate over one bounded proxy request.
func (c *Client) DigestUpdate(session raw.SessionHandle, data []byte) error {
	return c.invoke("DigestUpdate", []any{session, data})
}

// DigestKey forwards raw.Module.DigestKey over one bounded proxy request.
func (c *Client) DigestKey(session raw.SessionHandle, key raw.ObjectHandle) error {
	return c.invoke("DigestKey", []any{session, key})
}

// DigestFinal forwards raw.Module.DigestFinal over one bounded proxy request.
func (c *Client) DigestFinal(session raw.SessionHandle) ([]byte, error) {
	var result0 []byte
	err := c.invoke("DigestFinal", []any{session}, &result0)
	return result0, err
}

// SignInit forwards raw.Module.SignInit over one bounded proxy request.
func (c *Client) SignInit(session raw.SessionHandle, mechanisms []*raw.Mechanism, key raw.ObjectHandle) error {
	return c.invoke("SignInit", []any{session, mechanisms, key})
}

// Sign forwards raw.Module.Sign over one bounded proxy request.
func (c *Client) Sign(session raw.SessionHandle, data []byte) ([]byte, error) {
	var result0 []byte
	err := c.invoke("Sign", []any{session, data}, &result0)
	return result0, err
}

// SignUpdate forwards raw.Module.SignUpdate over one bounded proxy request.
func (c *Client) SignUpdate(session raw.SessionHandle, data []byte) error {
	return c.invoke("SignUpdate", []any{session, data})
}

// SignFinal forwards raw.Module.SignFinal over one bounded proxy request.
func (c *Client) SignFinal(session raw.SessionHandle) ([]byte, error) {
	var result0 []byte
	err := c.invoke("SignFinal", []any{session}, &result0)
	return result0, err
}

// SignRecoverInit forwards raw.Module.SignRecoverInit over one bounded proxy request.
func (c *Client) SignRecoverInit(session raw.SessionHandle, mechanisms []*raw.Mechanism, key raw.ObjectHandle) error {
	return c.invoke("SignRecoverInit", []any{session, mechanisms, key})
}

// SignRecover forwards raw.Module.SignRecover over one bounded proxy request.
func (c *Client) SignRecover(session raw.SessionHandle, data []byte) ([]byte, error) {
	var result0 []byte
	err := c.invoke("SignRecover", []any{session, data}, &result0)
	return result0, err
}

// VerifyInit forwards raw.Module.VerifyInit over one bounded proxy request.
func (c *Client) VerifyInit(session raw.SessionHandle, mechanisms []*raw.Mechanism, key raw.ObjectHandle) error {
	return c.invoke("VerifyInit", []any{session, mechanisms, key})
}

// Verify forwards raw.Module.Verify over one bounded proxy request.
func (c *Client) Verify(session raw.SessionHandle, data, signature []byte) error {
	return c.invoke("Verify", []any{session, data, signature})
}

// VerifyUpdate forwards raw.Module.VerifyUpdate over one bounded proxy request.
func (c *Client) VerifyUpdate(session raw.SessionHandle, data []byte) error {
	return c.invoke("VerifyUpdate", []any{session, data})
}

// VerifyFinal forwards raw.Module.VerifyFinal over one bounded proxy request.
func (c *Client) VerifyFinal(session raw.SessionHandle, signature []byte) error {
	return c.invoke("VerifyFinal", []any{session, signature})
}

// VerifyRecoverInit forwards raw.Module.VerifyRecoverInit over one bounded proxy request.
func (c *Client) VerifyRecoverInit(session raw.SessionHandle, mechanisms []*raw.Mechanism, key raw.ObjectHandle) error {
	return c.invoke("VerifyRecoverInit", []any{session, mechanisms, key})
}

// VerifyRecover forwards raw.Module.VerifyRecover over one bounded proxy request.
func (c *Client) VerifyRecover(session raw.SessionHandle, signature []byte) ([]byte, error) {
	var result0 []byte
	err := c.invoke("VerifyRecover", []any{session, signature}, &result0)
	return result0, err
}

// DigestEncryptUpdate forwards raw.Module.DigestEncryptUpdate over one bounded proxy request.
func (c *Client) DigestEncryptUpdate(session raw.SessionHandle, data []byte) ([]byte, error) {
	var result0 []byte
	err := c.invoke("DigestEncryptUpdate", []any{session, data}, &result0)
	return result0, err
}

// DecryptDigestUpdate forwards raw.Module.DecryptDigestUpdate over one bounded proxy request.
func (c *Client) DecryptDigestUpdate(session raw.SessionHandle, data []byte) ([]byte, error) {
	var result0 []byte
	err := c.invoke("DecryptDigestUpdate", []any{session, data}, &result0)
	return result0, err
}

// SignEncryptUpdate forwards raw.Module.SignEncryptUpdate over one bounded proxy request.
func (c *Client) SignEncryptUpdate(session raw.SessionHandle, data []byte) ([]byte, error) {
	var result0 []byte
	err := c.invoke("SignEncryptUpdate", []any{session, data}, &result0)
	return result0, err
}

// DecryptVerifyUpdate forwards raw.Module.DecryptVerifyUpdate over one bounded proxy request.
func (c *Client) DecryptVerifyUpdate(session raw.SessionHandle, data []byte) ([]byte, error) {
	var result0 []byte
	err := c.invoke("DecryptVerifyUpdate", []any{session, data}, &result0)
	return result0, err
}

// GenerateKey forwards raw.Module.GenerateKey over one bounded proxy request.
func (c *Client) GenerateKey(session raw.SessionHandle, mechanisms []*raw.Mechanism, attributes []*raw.Attribute) (raw.ObjectHandle, error) {
	var result0 raw.ObjectHandle
	err := c.invoke("GenerateKey", []any{session, mechanisms, attributes}, &result0)
	return result0, err
}

// GenerateKeyPair forwards raw.Module.GenerateKeyPair over one bounded proxy request.
func (c *Client) GenerateKeyPair(session raw.SessionHandle, mechanisms []*raw.Mechanism, publicAttributes, privateAttributes []*raw.Attribute) (raw.ObjectHandle, raw.ObjectHandle, error) {
	var result0 raw.ObjectHandle
	var result1 raw.ObjectHandle
	err := c.invoke("GenerateKeyPair", []any{session, mechanisms, publicAttributes, privateAttributes}, &result0, &result1)
	return result0, result1, err
}

// WrapKey forwards raw.Module.WrapKey over one bounded proxy request.
func (c *Client) WrapKey(session raw.SessionHandle, mechanisms []*raw.Mechanism, wrappingKey, key raw.ObjectHandle) ([]byte, error) {
	var result0 []byte
	err := c.invoke("WrapKey", []any{session, mechanisms, wrappingKey, key}, &result0)
	return result0, err
}

// UnwrapKey forwards raw.Module.UnwrapKey over one bounded proxy request.
func (c *Client) UnwrapKey(session raw.SessionHandle, mechanisms []*raw.Mechanism, unwrappingKey raw.ObjectHandle, wrapped []byte, attributes []*raw.Attribute) (raw.ObjectHandle, error) {
	var result0 raw.ObjectHandle
	err := c.invoke("UnwrapKey", []any{session, mechanisms, unwrappingKey, wrapped, attributes}, &result0)
	return result0, err
}

// DeriveKey forwards raw.Module.DeriveKey over one bounded proxy request.
func (c *Client) DeriveKey(session raw.SessionHandle, mechanisms []*raw.Mechanism, baseKey raw.ObjectHandle, attributes []*raw.Attribute) (raw.ObjectHandle, error) {
	var result0 raw.ObjectHandle
	err := c.invoke("DeriveKey", []any{session, mechanisms, baseKey, attributes}, &result0)
	return result0, err
}

// SeedRandom forwards raw.Module.SeedRandom over one bounded proxy request.
func (c *Client) SeedRandom(session raw.SessionHandle, seed []byte) error {
	return c.invoke("SeedRandom", []any{session, seed})
}

// GenerateRandom forwards raw.Module.GenerateRandom over one bounded proxy request.
func (c *Client) GenerateRandom(session raw.SessionHandle, length int) ([]byte, error) {
	var result0 []byte
	err := c.invoke("GenerateRandom", []any{session, length}, &result0)
	return result0, err
}

// MessageEncryptInit forwards raw.Module.MessageEncryptInit over one bounded proxy request.
func (c *Client) MessageEncryptInit(session raw.SessionHandle, mechanisms []*raw.Mechanism, key raw.ObjectHandle) error {
	return c.invoke("MessageEncryptInit", []any{session, mechanisms, key})
}

// EncryptMessage forwards raw.Module.EncryptMessage over one bounded proxy request.
func (c *Client) EncryptMessage(session raw.SessionHandle, parameter any, associatedData, plaintext []byte) ([]byte, error) {
	var result0 []byte
	err := c.invoke("EncryptMessage", []any{session, parameter, associatedData, plaintext}, &result0)
	return result0, err
}

// EncryptMessageBegin forwards raw.Module.EncryptMessageBegin over one bounded proxy request.
func (c *Client) EncryptMessageBegin(session raw.SessionHandle, parameter any, associatedData []byte) error {
	return c.invoke("EncryptMessageBegin", []any{session, parameter, associatedData})
}

// EncryptMessageNext forwards raw.Module.EncryptMessageNext over one bounded proxy request.
func (c *Client) EncryptMessageNext(session raw.SessionHandle, parameter any, plaintext []byte, flags uint) ([]byte, error) {
	var result0 []byte
	err := c.invoke("EncryptMessageNext", []any{session, parameter, plaintext, flags}, &result0)
	return result0, err
}

// MessageEncryptFinal forwards raw.Module.MessageEncryptFinal over one bounded proxy request.
func (c *Client) MessageEncryptFinal(session raw.SessionHandle) error {
	return c.invoke("MessageEncryptFinal", []any{session})
}

// MessageDecryptInit forwards raw.Module.MessageDecryptInit over one bounded proxy request.
func (c *Client) MessageDecryptInit(session raw.SessionHandle, mechanisms []*raw.Mechanism, key raw.ObjectHandle) error {
	return c.invoke("MessageDecryptInit", []any{session, mechanisms, key})
}

// DecryptMessage forwards raw.Module.DecryptMessage over one bounded proxy request.
func (c *Client) DecryptMessage(session raw.SessionHandle, parameter any, associatedData, ciphertext []byte) ([]byte, error) {
	var result0 []byte
	err := c.invoke("DecryptMessage", []any{session, parameter, associatedData, ciphertext}, &result0)
	return result0, err
}

// DecryptMessageBegin forwards raw.Module.DecryptMessageBegin over one bounded proxy request.
func (c *Client) DecryptMessageBegin(session raw.SessionHandle, parameter any, associatedData []byte) error {
	return c.invoke("DecryptMessageBegin", []any{session, parameter, associatedData})
}

// DecryptMessageNext forwards raw.Module.DecryptMessageNext over one bounded proxy request.
func (c *Client) DecryptMessageNext(session raw.SessionHandle, parameter any, ciphertext []byte, flags uint) ([]byte, error) {
	var result0 []byte
	err := c.invoke("DecryptMessageNext", []any{session, parameter, ciphertext, flags}, &result0)
	return result0, err
}

// MessageDecryptFinal forwards raw.Module.MessageDecryptFinal over one bounded proxy request.
func (c *Client) MessageDecryptFinal(session raw.SessionHandle) error {
	return c.invoke("MessageDecryptFinal", []any{session})
}

// MessageSignInit forwards raw.Module.MessageSignInit over one bounded proxy request.
func (c *Client) MessageSignInit(session raw.SessionHandle, mechanisms []*raw.Mechanism, key raw.ObjectHandle) error {
	return c.invoke("MessageSignInit", []any{session, mechanisms, key})
}

// SignMessage forwards raw.Module.SignMessage over one bounded proxy request.
func (c *Client) SignMessage(session raw.SessionHandle, parameter any, data []byte) ([]byte, error) {
	var result0 []byte
	err := c.invoke("SignMessage", []any{session, parameter, data}, &result0)
	return result0, err
}

// SignMessageBegin forwards raw.Module.SignMessageBegin over one bounded proxy request.
func (c *Client) SignMessageBegin(session raw.SessionHandle, parameter any) error {
	return c.invoke("SignMessageBegin", []any{session, parameter})
}

// SignMessageNext forwards raw.Module.SignMessageNext over one bounded proxy request.
func (c *Client) SignMessageNext(session raw.SessionHandle, parameter any, data []byte) ([]byte, error) {
	var result0 []byte
	err := c.invoke("SignMessageNext", []any{session, parameter, data}, &result0)
	return result0, err
}

// MessageSignFinal forwards raw.Module.MessageSignFinal over one bounded proxy request.
func (c *Client) MessageSignFinal(session raw.SessionHandle) error {
	return c.invoke("MessageSignFinal", []any{session})
}

// MessageVerifyInit forwards raw.Module.MessageVerifyInit over one bounded proxy request.
func (c *Client) MessageVerifyInit(session raw.SessionHandle, mechanisms []*raw.Mechanism, key raw.ObjectHandle) error {
	return c.invoke("MessageVerifyInit", []any{session, mechanisms, key})
}

// VerifyMessage forwards raw.Module.VerifyMessage over one bounded proxy request.
func (c *Client) VerifyMessage(session raw.SessionHandle, parameter any, data, signature []byte) error {
	return c.invoke("VerifyMessage", []any{session, parameter, data, signature})
}

// VerifyMessageBegin forwards raw.Module.VerifyMessageBegin over one bounded proxy request.
func (c *Client) VerifyMessageBegin(session raw.SessionHandle, parameter any) error {
	return c.invoke("VerifyMessageBegin", []any{session, parameter})
}

// VerifyMessageNext forwards raw.Module.VerifyMessageNext over one bounded proxy request.
func (c *Client) VerifyMessageNext(session raw.SessionHandle, parameter any, data, signature []byte) error {
	return c.invoke("VerifyMessageNext", []any{session, parameter, data, signature})
}

// MessageVerifyFinal forwards raw.Module.MessageVerifyFinal over one bounded proxy request.
func (c *Client) MessageVerifyFinal(session raw.SessionHandle) error {
	return c.invoke("MessageVerifyFinal", []any{session})
}

// EncapsulateKey forwards raw.Module.EncapsulateKey over one bounded proxy request.
func (c *Client) EncapsulateKey(session raw.SessionHandle, mechanisms []*raw.Mechanism, publicKey raw.ObjectHandle, attributes []*raw.Attribute) ([]byte, raw.ObjectHandle, error) {
	var result0 []byte
	var result1 raw.ObjectHandle
	err := c.invoke("EncapsulateKey", []any{session, mechanisms, publicKey, attributes}, &result0, &result1)
	return result0, result1, err
}

// DecapsulateKey forwards raw.Module.DecapsulateKey over one bounded proxy request.
func (c *Client) DecapsulateKey(session raw.SessionHandle, mechanisms []*raw.Mechanism, privateKey raw.ObjectHandle, ciphertext []byte, attributes []*raw.Attribute) (raw.ObjectHandle, error) {
	var result0 raw.ObjectHandle
	err := c.invoke("DecapsulateKey", []any{session, mechanisms, privateKey, ciphertext, attributes}, &result0)
	return result0, err
}

// VerifySignatureInit forwards raw.Module.VerifySignatureInit over one bounded proxy request.
func (c *Client) VerifySignatureInit(session raw.SessionHandle, mechanisms []*raw.Mechanism, key raw.ObjectHandle, signature []byte) error {
	return c.invoke("VerifySignatureInit", []any{session, mechanisms, key, signature})
}

// VerifySignature forwards raw.Module.VerifySignature over one bounded proxy request.
func (c *Client) VerifySignature(session raw.SessionHandle, data []byte) error {
	return c.invoke("VerifySignature", []any{session, data})
}

// VerifySignatureUpdate forwards raw.Module.VerifySignatureUpdate over one bounded proxy request.
func (c *Client) VerifySignatureUpdate(session raw.SessionHandle, data []byte) error {
	return c.invoke("VerifySignatureUpdate", []any{session, data})
}

// VerifySignatureFinal forwards raw.Module.VerifySignatureFinal over one bounded proxy request.
func (c *Client) VerifySignatureFinal(session raw.SessionHandle) error {
	return c.invoke("VerifySignatureFinal", []any{session})
}

// GetSessionValidationFlags forwards raw.Module.GetSessionValidationFlags over one bounded proxy request.
func (c *Client) GetSessionValidationFlags(session raw.SessionHandle, typ raw.ValidationFlagsType) (raw.Flags, error) {
	var result0 raw.Flags
	err := c.invoke("GetSessionValidationFlags", []any{session, typ}, &result0)
	return result0, err
}

// AsyncComplete forwards raw.Module.AsyncComplete over one bounded proxy request.
func (c *Client) AsyncComplete(session raw.SessionHandle, functionName string, result *raw.AsyncData) error {
	return c.invoke("AsyncComplete", []any{session, functionName, result})
}

// AsyncGetID forwards raw.Module.AsyncGetID over one bounded proxy request.
func (c *Client) AsyncGetID(session raw.SessionHandle, functionName string) (uint, error) {
	var result0 uint
	err := c.invoke("AsyncGetID", []any{session, functionName}, &result0)
	return result0, err
}

// AsyncJoin forwards raw.Module.AsyncJoin over one bounded proxy request.
func (c *Client) AsyncJoin(session raw.SessionHandle, functionName string, id uint, data []byte) error {
	return c.invoke("AsyncJoin", []any{session, functionName, id, data})
}

// WrapKeyAuthenticated forwards raw.Module.WrapKeyAuthenticated over one bounded proxy request.
func (c *Client) WrapKeyAuthenticated(session raw.SessionHandle, mechanisms []*raw.Mechanism, wrappingKey, key raw.ObjectHandle, associatedData []byte) ([]byte, error) {
	var result0 []byte
	err := c.invoke("WrapKeyAuthenticated", []any{session, mechanisms, wrappingKey, key, associatedData}, &result0)
	return result0, err
}

// UnwrapKeyAuthenticated forwards raw.Module.UnwrapKeyAuthenticated over one bounded proxy request.
func (c *Client) UnwrapKeyAuthenticated(session raw.SessionHandle, mechanisms []*raw.Mechanism, unwrappingKey raw.ObjectHandle, wrapped []byte, attributes []*raw.Attribute, associatedData []byte) (raw.ObjectHandle, error) {
	var result0 raw.ObjectHandle
	err := c.invoke("UnwrapKeyAuthenticated", []any{session, mechanisms, unwrappingKey, wrapped, attributes, associatedData}, &result0)
	return result0, err
}
